parserOptions: 
  ecmaVersion: 2019
  sourceType: module
env:
  es6: true
  browser: true
plugins:
  - 'svelte3'
extends:
  - 'eslint:recommended'
overrides:
  - files:
      - '**/*.svelte'
    processor: 'svelte3/svelte3'
rules:
  no-trailing-spaces: error
  indent:
    - error
    - 4
