root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: none
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "_"
  "@typescript-eslint/explicit-function-return-type": "off"

  no-trailing-spaces: error